apiVersion: apps/v1
kind: Deployment
metadata:
  name: pda

spec:
  replicas: 3
  selector:
    matchLabels:
      app: pda
  template:
    metadata:
      labels:
        app: pda

    spec:
      containers:
        - name: pda-container
          image: jp.icr.io/pda-01/pda-testing
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP